name: example
description: example for this dart API
version: 0.0.2
homepage: https://github.com/openfoodfacts/openfoodfacts-dart
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  openfoodfacts:
    path: ../

dev_dependencies:
  test: any
