name: example
description: example for this dart API
version: 0.0.1
author: Alexander Schacht <grumpf@gmx.de>
homepage: https://github.com/Grumpf86/openfoodfacts-dart

environment:
  sdk: '>=2.0.0-dev.54.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  openfoodfacts: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# https://www.dartlang.org/tools/pub/pubspec

flutter: