name: openfoodfacts
description: Dart package for the Open Food Facts API, a food products database made by everyone, for everyone.
# The version is automatically, temporarily increased by the release workflow, changing it manually has no effect.
version: 3.29.0
homepage: https://github.com/openfoodfacts/openfoodfacts-dart

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  json_annotation: ^4.9.0
  http: ^1.5.0
  http_parser: ^4.1.2
  path: ^1.9.1
  meta: ^1.17.0

dev_dependencies:
  analyzer: 8.1.1
  build_runner: 2.10.4
  json_serializable: 6.11.2
  lints: 6.0.0
  test: 1.29.0
  coverage: 1.15.0

funding:
  - "https://donate.openfoodfacts.org/"
  - "https://opencollective.com/openfoodfacts-server"

# 5 topics max
# cf. https://dart.dev/tools/pub/pubspec#topics
topics:
  - nutriscore
  - ecoscore
  - nutrition
  - food
  - ingredients
