name: openfoodfacts
description: Dart package for the Open Food Facts API, a food products database made by everyone, for everyone.
version: 0.3.12+1
#authors:
#- Alexander Schacht <grumpf@gmx.de>
#- Primaël Quémerais <primael@reefind.com>
#- Marcus Cantu
#- Peter Tran-Jørgensen
homepage: https://github.com/openfoodfacts/openfoodfacts-dart

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  async_loader: ^0.1.2
  json_annotation: ^3.1.0
  http: ^0.12.0
  path: ^1.7.0
  image: ^2.1.4

dev_dependencies:
  build_runner: ^1.10.1
  json_serializable: ^3.5.0
  flutter_test:
    sdk: flutter

# https://www.dartlang.org/tools/pub/pubspec
flutter:
  assets:
    - assets/json/
