name: openfoodfacts
description: Dart package for the Open Food Facts API, a food products database made by everyone, for everyone.
# The version is automatically, temporarily increased by the release workflow, changing it manually has no effect.
version: 3.4.0
homepage: https://github.com/openfoodfacts/openfoodfacts-dart

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  json_annotation: ^4.8.1
  http: '>=0.13.5 <2.0.0'
  http_parser: ^4.0.2
  path: ^1.8.2 # 1.8.2 for flutter_test as of 2023-04-06
  meta: ^1.8.0

dev_dependencies:
  analyzer: ^6.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.21.4
  coverage: ^1.6.2

funding:
  - "https://donate.openfoodfacts.org/"
  - "https://opencollective.com/openfoodfacts-server"

# 5 topics max
# cf. https://dart.dev/tools/pub/pubspec#topics
topics:
  - nutriscore
  - ecoscore
  - nutrition
  - food
  - ingredients
