name: openfoodfacts
description: Dart package for the Open Food Facts API, a food products database made by everyone, for everyone.
# The version is automatically, temporarily increased by the release workflow, changing it manually has no effect.
version: 3.27.0
homepage: https://github.com/openfoodfacts/openfoodfacts-dart

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  json_annotation: ^4.9.0
  http: '>=0.13.5 <2.0.0'
  http_parser: ^4.0.2
  path: ^1.9.0
  meta: ^1.8.0

dev_dependencies:
  analyzer: 7.7.0
  build_runner: 2.5.4
  json_serializable: 6.9.5
  lints: ">=3.0.0 <7.0.0"
  test: 1.26.3
  coverage: 1.15.0

funding:
  - "https://donate.openfoodfacts.org/"
  - "https://opencollective.com/openfoodfacts-server"

# 5 topics max
# cf. https://dart.dev/tools/pub/pubspec#topics
topics:
  - nutriscore
  - ecoscore
  - nutrition
  - food
  - ingredients
