name: openfoodfacts
description: Dart package for the Open Food Facts API, a food products database made by everyone, for everyone.
# The version is automatically, temporarily increased by the release workflow, changing it manually has no effect.
version: 1.0.0
homepage: https://github.com/openfoodfacts/openfoodfacts-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: ^4.4.0
  http: ^0.13.3
  path: ^1.8.0
  image: ^3.1.3
  meta: ^1.7.0

dev_dependencies:
  analyzer: ">=4.0.0 <5.0.0"
  build_runner: ^2.1.10
  json_serializable: ^6.1.6
  lints: ^1.0.1
  test: ^1.21.0
  coverage: ^1.2.0
