name: openfoodfacts
description: Dart package for the Open Food Facts API, a food products database made by everyone, for everyone.
version: 1.3.2
homepage: https://github.com/openfoodfacts/openfoodfacts-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: ^4.0.1
  http: ^0.13.3
  path: ^1.8.0
  image: ^3.0.2

dev_dependencies:
  analyzer: ^2.0.0
  build_runner: ^2.0.6
  json_serializable: ^5.0.0
  pedantic: ^1.11.1
  test: ^1.17.10
