name: test-sdk

on: [push, pull_request]

concurrency: 
  group: tests

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Chekout code
      uses: actions/checkout@v3

    - name: Setup Dart
      uses: dart-lang/setup-dart@v1

    - name: Install dependencies
      run: dart pub get

    - name: Check for formatting issues (run "flutter format . ")
      run: dart format --set-exit-if-changed .

    - name: Analyze project
      run: dart analyze

    - name: Run tests
      run: dart test test/

